Update VisualBukkitApp.java
error checks after calling DiscordCreate() and before accessing activityManager

it will fix this error (i hope):
An unexpected error occurred
java.lang.NullPointerException: Cannot invoke "discord_game_sdk.IDiscordCore$get_activity_manager_callback.apply(discord_game_sdk.IDiscordCore)" because "core[0].get_activity_manager" is null
	at com.gmail.visualbukkit.VisualBukkitApp.updateDiscordActivity(VisualBukkitApp.java:456)
	at com.gmail.visualbukkit.VisualBukkitApp.lambda$start$26(VisualBukkitApp.java:265)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:185)
	at java.base/java.lang.Thread.run(Thread.java:1583)